---
version: "3.7"

services:
  mongodbsrv:
    image: mongo:latest
    networks:
      - code4cwb_lan
  web:
    environment:
      ONIBUSIO_DB_HIST: onibus-historico
      ONIBUSIO_DB_URL: mongodb://mongodbsrv:27017/onibus-historico
      PORT: 3000
    build:
      context: .
      dockerfile: Dockerfile-development
    networks:
      - code4cwb_lan
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mongodbsrv

networks:
  code4cwb_lan:
    driver: bridge
