---
version: "3.7"

services:
  mongodbsrv:
    image: mongo:latest
    networks:
      - code4cwb_lan
  mongodbimport:
    environment:
      MONGODB_SERVER: mongodbsrv
      MONGODB_DATABASE: onibus-historico
    image: mongo:latest
    networks:
      - code4cwb_lan
    volumes:
      - .:/app
    working_dir: /app
    command: ./load_data.sh
    depends_on:
      - mongodbsrv
  web:
    environment:
      ONIBUSIO_DB_HIST: onibus-historico
      ONIBUSIO_DB_URL: mongodb://mongodbsrv:27017/onibus-historico
      PORT: 3000
    build:
      context: .
      dockerfile: Dockerfile-development
    networks:
      - code4cwb_lan
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mongodbsrv
      - mongodbimport
networks:
  code4cwb_lan:
    driver: bridge
